<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yf</groupId>
        <artifactId>yf-websocket</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>yf-websocket-redis</artifactId>

    <dependencies>
        <!--   微服务项目建议远程调用，而不是引入     -->
        <dependency>
            <groupId>com.yf</groupId>
            <artifactId>yf-system</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

</project>