<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yf</groupId>
        <artifactId>yf-integration</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>yf-file</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
        </dependency>

        <!--   file-oss-qiniu         -->
        <dependency>
            <groupId>com.qiniu</groupId>
            <artifactId>qiniu-java-sdk</artifactId>
        </dependency>

        <!--   file-oss-aliyun         -->
        <dependency>
            <groupId>com.aliyun.oss</groupId>
            <artifactId>aliyun-sdk-oss</artifactId>
        </dependency>
        <!--   file-cos-tencent         -->
        <dependency>
            <groupId>com.qcloud</groupId>
            <artifactId>cos_api</artifactId>
        </dependency>
        <!--   file-obs-huawei         -->
        <dependency>
            <groupId>com.huaweicloud</groupId>
            <artifactId>esdk-obs-java</artifactId>
        </dependency>

        <dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/clojure-interop/org.tensorflow.framework -->
        <!-- https://mvnrepository.com/artifact/org.tensorflow/tensorflow-framework -->
        <!--        <dependency>-->
        <!--            <groupId>org.tensorflow</groupId>-->
        <!--            <artifactId>tensorflow-framework</artifactId>-->
        <!--            <version>0.5.0</version>-->
        <!--        </dependency>-->

        <!--        <dependency>-->
        <!--            <groupId>org.bytedeco</groupId>-->
        <!--            <artifactId>opencv</artifactId>-->
        <!--            <version>4.9.0-1.5.10</version>-->
        <!--        </dependency>-->

    </dependencies>
</project>